import { writeFileSync } from "node:fs";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  HiArrowPath,
  HiOutlineBeaker,
  HiOutlineBolt,
  HiOutlineChartBar,
  HiOutlineCheckCircle,
  HiOutlineClock,
  HiOutlineCloudArrowUp,
  HiOutlineCpuChip,
  HiOutlineDocumentPlus,
  HiOutlineDocumentText,
  HiOutlineFingerPrint,
  HiOutlineFolderOpen,
  HiOutlinePlay,
  HiOutlinePresentationChartLine,
  HiOutlineServerStack,
  HiOutlineSignal,
  HiOutlineTableCells,
} from "react-icons/hi2";

const ICONS = {
  brand: HiOutlineCpuChip,
  server: HiOutlineServerStack,
  signal: HiOutlineSignal,
  status: HiOutlineCheckCircle,
  busy: HiArrowPath,
  goodput: HiOutlineBolt,
  time: HiOutlineClock,
  retry: HiArrowPath,
  hash: HiOutlineFingerPrint,
  file: HiOutlineFolderOpen,
  upload: HiOutlineCloudArrowUp,
  add: HiOutlineDocumentPlus,
  play: HiOutlinePlay,
  experiment: HiOutlineBeaker,
  analysis: HiOutlineChartBar,
  report: HiOutlineDocumentText,
  log: HiOutlineTableCells,
  charts: HiOutlinePresentationChartLine,
};

const entries = Object.entries(ICONS).map(([name, Icon]) => {
  const svg = renderToStaticMarkup(createElement(Icon, { size: 18, "aria-hidden": true }));
  return `  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`;
});

const content = `// Auto-generated by npm run build:icons. Do not edit manually.
window.NPIcons = {
${entries.join("\n")}
};

window.mountNPIcons = function mountNPIcons() {
  document.querySelectorAll("[data-icon]").forEach((node) => {
    const name = node.dataset.icon;
    if (window.NPIcons[name]) {
      node.innerHTML = window.NPIcons[name];
    }
  });
};
`;

writeFileSync(new URL("../web/static/js/icons.js", import.meta.url), content);
